### ISSUE TITLE
[ FEATURE ] 아이콘 드래그 앤 드랍

### ISSUE THREAD

**Issue by joohaem** [Fightim/client-gui#1]
## TASK
- [x] 아이콘 드래그 앤 드랍 기능을 구현합니다.
- [x] `mousedown`, `move`, `mouseup` 이벤트를 이용해 각각의 동작을 구현합니다.
- [x] 각각의 이벤트 핸들러를 구현합니다
  - [x] context 를 이용하여 active 되는 인스턴스를 표시하는 데이터를 구성합니다
  - [x] dragstart :: 설정 가능한 box에 active 표시
  - [x] drop :: 해당 인스턴스를 context 데이터에 추가
  - [x] drop :: UI에 추가
- [x] 인스턴스 아이콘 (max 2) 이 Active 상태일 때의 레이아웃을 구성합니다.

**Comment by joohaem** [comment]
target - `draggable="true`

- **Events fired on the draggable target** (the source element)**:**
    - [ondragstart](https://www.w3schools.com/jsref/event_[ondrag](https://www.w3schools.com/jsref/event_ondrag.asp)start.asp) - occurs when the user starts to drag an element
    - [ondrag](https://www.w3schools.com/jsref/event_ondrag.asp) - occurs when an element is being dragged
    - [ondragend](https://www.w3schools.com/jsref/event_ondragend.asp) - occurs when the user has finished dragging the element
- **Events fired on the drop target:**
    - [ondragenter](https://www.w3schools.com/jsref/event_ondragenter.asp) - occurs when the dragged element enters the drop target
    - [ondragleave](https://www.w3schools.com/jsref/event_ondragleave.asp) - occurs when the dragged element leaves the drop target
    - [ondrop](https://www.w3schools.com/jsref/event_ondrop.asp) - occurs when the dragged element is dropped on the drop target
        - [ondragover](https://www.w3schools.com/jsref/event_ondragover.asp) - occurs when the dragged element is over the drop target → `preventDefault` 필수

**Comment by joohaem** [comment]
> #EFC42B yellow100

active effect :: `box-shadow: 0px 0px 8px 4px rgba(239, 196, 43, 0.4);`

**Comment by joohaem** [comment]
Complete on commit 🔗 ce5373474f85212742bb6ca489574b172a619e3b
